version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lisa-massage-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"